import { createHash, randomBytes, timingSafeEqual } from "node:crypto";
import type { StaffSql } from "@/lib/staff/db";
import { withOrg } from "@/lib/staff/db";
import { ROOT_URL } from "@/lib/site";

// Time-limited read-only access for an inspector.
//
// THE TOKEN IS A BEARER CREDENTIAL WITH NO SECOND FACTOR. Whoever holds
// the URL is the inspector as far as this system is concerned, which
// sets every other decision here: 256 bits of entropy so it cannot be
// guessed, only its hash stored so a database dump yields nothing, a
// hard expiry so a forgotten link closes itself, and instant revocation
// for the ones that do not.

/** 32 random bytes, base64url. Not a UUID: a v4 UUID carries 122 bits
 *  and is generated by machinery tuned for uniqueness rather than
 *  unpredictability, which is the wrong property for a credential. */
export function mintToken(): string {
  return randomBytes(32).toString("base64url");
}

export function hashToken(token: string): string {
  return createHash("sha256").update(token).digest("hex");
}

/** Constant-time compare, for the places a hash is checked in
 *  application code rather than by an indexed lookup. */
export function hashesEqual(a: string, b: string): boolean {
  const ba = Buffer.from(a, "utf8");
  const bb = Buffer.from(b, "utf8");
  if (ba.length !== bb.length) return false;
  return timingSafeEqual(ba, bb);
}

export interface IssuedLink {
  id: string;
  url: string;
  expiresAt: string;
}

/** Issue a link. Returns the token ONCE — it is never retrievable
 *  afterwards, because only its hash is stored. A lost link is reissued,
 *  not recovered, and that is deliberate: a bearer token an
 *  administrator can read back is one they can be talked into reading
 *  out. */
export async function issueLink(
  sql: StaffSql,
  args: { org: string; label: string; hours: number; createdBy: string }
): Promise<IssuedLink> {
  const token = mintToken();
  const [row] = await sql<{ id: string; expires_at: string }[]>`
    insert into staff.surveyor_tokens
      (org_slug, token_hash, label, expires_at, created_by)
    values
      (${args.org}, ${hashToken(token)}, ${args.label},
       now() + make_interval(hours => ${args.hours}), ${args.createdBy})
    returning id, expires_at::text as expires_at
  `;
  return {
    id: row.id,
    url: `${ROOT_URL}/surveyor/${token}`,
    expiresAt: row.expires_at,
  };
}

export interface SurveyorContext {
  org: string;
  label: string;
  expiresAt: string;
}

/**
 * Turn a token into an org, or null.
 *
 * NO SESSION EXISTS HERE, so there is no org to scope RLS by until this
 * has run — the org is the answer, not an input. staff.redeem_surveyor_token
 * is SECURITY DEFINER for exactly that reason and does nothing else: one
 * hash in, one org slug out, expiry and revocation evaluated in the same
 * statement so no window exists where application code holds a
 * valid-looking org from a dead link.
 *
 * The role passed to withOrg is 'surveyor', NOT an admin role, so
 * staff.is_super_admin() is false and every subsequent read is scoped by
 * ordinary org isolation.
 */
export async function redeem(token: string): Promise<SurveyorContext | null> {
  // Cheap shape check first. A 43-character base64url string is the only
  // thing that can possibly match, so anything else avoids a query.
  if (!/^[A-Za-z0-9_-]{43}$/.test(token)) return null;

  const rows = await withOrg("", "surveyor", (sql) =>
    sql<{ org_slug: string; label: string; expires_at: string }[]>`
      select org_slug, label, expires_at::text as expires_at
        from staff.redeem_surveyor_token(${hashToken(token)})
    `
  );
  const row = rows[0];
  if (!row) return null;
  return { org: row.org_slug, label: row.label, expiresAt: row.expires_at };
}

/** Read the compliance record as the inspector. Scoped to the redeemed
 *  org, as a non-admin, with no write path anywhere in the callback. */
export async function asSurveyor<T>(
  org: string,
  fn: (sql: StaffSql) => Promise<T>
): Promise<T> {
  return withOrg(org, "surveyor", fn);
}

export async function revokeLink(
  sql: StaffSql,
  args: { id: string; by: string }
): Promise<boolean> {
  const rows = await sql<{ id: string }[]>`
    update staff.surveyor_tokens
       set revoked_at = now(), revoked_by = ${args.by}
     where id = ${args.id} and revoked_at is null
    returning id
  `;
  return rows.length > 0;
}

export interface AccessRow {
  id: string;
  label: string;
  created_at: string;
  expires_at: string;
  revoked_at: string | null;
  first_seen_at: string | null;
  last_seen_at: string | null;
  view_count: number;
  created_by_name: string | null;
  revoked_by_name: string | null;
  state: "active" | "expired" | "revoked" | "unopened";
  seconds_left: number;
}

export async function issuedLinks(sql: StaffSql): Promise<AccessRow[]> {
  return sql<AccessRow[]>`
    select id, label,
           created_at::text as created_at,
           expires_at::text as expires_at,
           revoked_at::text as revoked_at,
           first_seen_at::text as first_seen_at,
           last_seen_at::text as last_seen_at,
           view_count, created_by_name, revoked_by_name, state, seconds_left
      from staff.surveyor_access
     order by created_at desc
     limit 50
  `;
}
