#!/usr/bin/env bash
# Regenerates supabase/staff-setup-all.sql from the individual migrations.
#
# The combined file exists so setup is one paste into the Supabase SQL
# editor rather than six ordered operations — which matters when the
# person running it is directing a laptop from their phone. It is
# generated rather than hand-maintained so it cannot drift from the files
# it is built out of.
#
# ORDER IS DEPENDENCY ORDER, not alphabetical. onboarding needs the
# staff.user_role enum from schema; the seeds need their tables; security
# alters columns the others created.
set -euo pipefail
cd "$(dirname "$0")/.."

PARTS=(staff-schema staff-onboarding staff-onboarding-seed staff-logs staff-logs-seed staff-security staff-single-domain staff-billing staff-trial)
OUT=supabase/staff-setup-all.sql

{
  sed -n '1,/^-- ====.*$/p' /dev/null   # placeholder so the heredoc below is the only header
  cat <<'HDR'
-- ============================================================
-- STAFF COMPLIANCE MODULE — complete setup, one file.
--
-- Paste the whole thing into the Supabase SQL editor and run once.
-- Idempotent end to end; running it twice is safe.
--
-- Does NOT touch the patient-side tables in the public schema —
-- supabase/schema.sql is separate.
--
-- GENERATED by scripts/build-staff-setup.sh. Edit the source migrations,
-- then re-run that script; do not edit this file directly.
--
-- Two things remain afterwards and neither can be done in SQL:
--   alter role staff_app with password '<generate one>';
--   insert into staff.org_invites (org_slug, email, role)
--     values ('afc', '<your work email>', 'org_admin');
-- ============================================================
HDR
  for f in "${PARTS[@]}"; do
    printf '\n\n-- ========== %s.sql ==========\n\n' "$f"
    cat "supabase/$f.sql"
  done
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines from ${#PARTS[@]} migrations)"
