#!/usr/bin/env bash
# Regenerates supabase/staff-setup-all.sql from the individual migrations.
#
# The combined file exists so setup is one paste into the Supabase SQL
# editor rather than six ordered operations — which matters when the
# person running it is directing a laptop from their phone. It is
# generated rather than hand-maintained so it cannot drift from the files
# it is built out of.
#
# ORDER IS DEPENDENCY ORDER, not alphabetical. onboarding needs the
# staff.user_role enum from schema; the seeds need their tables; security
# alters columns the others created.
set -euo pipefail
cd "$(dirname "$0")/.."

PARTS=(staff-schema staff-onboarding staff-onboarding-seed staff-logs staff-logs-seed staff-security staff-single-domain staff-billing staff-trial staff-obligations staff-obligations-seed staff-job-roles staff-job-roles-seed staff-credentials staff-credentials-seed staff-scope staff-scope-seed staff-rounds staff-rounds-seed staff-onboarding-wizard staff-onboarding-wizard-seed staff-documents staff-protocols staff-protocols-seed staff-emergency staff-emergency-seed staff-avatars staff-corrective-action staff-alerts staff-alerts-sms staff-surveyor staff-log-photos staff-email-auth staff-log-presets staff-eod-close staff-geofence staff-ethics staff-ops-manual staff-reports staff-facility staff-audio-audit staff-invites staff-signup-guard staff-immutability staff-amend staff-statutory-logs staff-credential-matrix staff-sharps-waste staff-provision-seed staff-org-settings staff-privacy-rules staff-optional-logs staff-seats staff-founder-job staff-multisite staff-eod-report)
OUT=supabase/staff-setup-all.sql

# A generated file only cannot drift if the generator knows what it is
# missing. Ten migrations had already been written and never added to the
# list above, so the combined file — the one a customer actually pastes —
# silently lacked them. Anything matching supabase/staff-*.sql that is not
# named in PARTS is a build failure, not a comment somebody has to notice.
missing=()
for f in supabase/staff-*.sql; do
  base=$(basename "$f" .sql)
  [ "$base" = staff-setup-all ] && continue
  listed=no
  for p in "${PARTS[@]}"; do [ "$p" = "$base" ] && listed=yes && break; done
  [ "$listed" = no ] && missing+=("$base")
done
if [ ${#missing[@]} -gt 0 ]; then
  echo "error: these migrations exist but are not in PARTS, so they would be" >&2
  echo "left out of $OUT. Add each one at its dependency position:" >&2
  printf '  %s\n' "${missing[@]}" >&2
  exit 1
fi

# A template is JSON in a SQL file, so Postgres accepts anything. The
# app then parses it with lib/staff/forms.ts, and a template that fails
# THAT parse seeds perfectly, appears on the board with a "Fill in"
# button, and 404s when somebody taps it. Four shipped that way. Nothing
# gets bundled until every template parses with the schema the app uses.
if command -v npx >/dev/null 2>&1; then
  npx tsx scripts/verify-templates.ts || {
    echo "error: refusing to build $OUT with a template the app cannot parse." >&2
    exit 1
  }
else
  echo "warning: npx not found — templates NOT verified against lib/staff/forms.ts" >&2
fi

{
  sed -n '1,/^-- ====.*$/p' /dev/null   # placeholder so the heredoc below is the only header
  cat <<'HDR'
-- ============================================================
-- STAFF COMPLIANCE MODULE — complete setup, one file.
--
-- Paste the whole thing into the Supabase SQL editor and run once.
-- Idempotent end to end; running it twice is safe.
--
-- Does NOT touch the patient-side tables in the public schema —
-- supabase/schema.sql is separate.
--
-- GENERATED by scripts/build-staff-setup.sh. Edit the source migrations,
-- then re-run that script; do not edit this file directly.
--
-- Two things remain afterwards and neither can be done in SQL:
--   alter role staff_app with password '<generate one>';
--   insert into staff.org_invites (org_slug, email, role)
--     values ('afc', '<your work email>', 'org_admin');
-- ============================================================
HDR
  for f in "${PARTS[@]}"; do
    printf '\n\n-- ========== %s.sql ==========\n\n' "$f"
    cat "supabase/$f.sql"
  done
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines from ${#PARTS[@]} migrations)"
