/**
 * Parses every form template in the migrations with the SAME schema the
 * app parses it with.
 *
 *   npx tsx scripts/verify-templates.ts
 *
 * WHY THIS EXISTS. A template is JSON in a SQL file, and Postgres will
 * accept any JSON at all. The application then parses it with
 * lib/staff/forms.ts, and when that parse fails loadTemplate() returns
 * null and the route answers 404. So a template can seed perfectly,
 * appear on the board with a "Fill in" button, and 404 the moment
 * somebody taps it — with nothing failing anywhere a developer would
 * look.
 *
 * That is not hypothetical. Four templates shipped that way: sharps-injury,
 * exposure-incident, hazcom-inventory and patient-complaint all used a
 * field type the schema did not define, and every one of them was a dead
 * link in production. Two more were written with a `standard` line over
 * the 400-character cap and would have shipped the same way.
 *
 * The gap is that the SQL side cannot see the Zod side. This closes it
 * by reading one and checking it against the other.
 *
 * EXIT CODES: 0 if every template parses, 1 otherwise.
 */

import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { formSchema } from "../lib/staff/forms";

const DIR = "supabase";

interface Found {
  file: string;
  slug: string;
  line: number;
  json: string;
}

/** Pulls out every `$json$ ... $json$` block and the template slug that
 *  precedes it. The seeds are generated by hand but consistently, so the
 *  slug is the second quoted string on the INSERT's value row. */
function templatesIn(file: string, sql: string): Found[] {
  const out: Found[] = [];
  const re = /\$json\$([\s\S]*?)\$json\$/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(sql)) !== null) {
    const before = sql.slice(0, m.index);
    // The nearest `('<org>', '<slug>',` above this block.
    const rows = [...before.matchAll(/\(\s*'[^']*'\s*,\s*'([a-z0-9-]+)'\s*,/g)];
    out.push({
      file,
      slug: rows.length ? rows[rows.length - 1][1] : "(unknown)",
      line: before.split("\n").length,
      json: m[1],
    });
  }
  return out;
}

let checked = 0;
let failed = 0;

for (const file of readdirSync(DIR).filter((f) => f.endsWith(".sql")).sort()) {
  // The combined bundle is these same files concatenated; checking it
  // too would only report every fault twice.
  if (file === "staff-setup-all.sql") continue;

  const sql = readFileSync(join(DIR, file), "utf8");
  for (const t of templatesIn(file, sql)) {
    let parsedJson: unknown;
    try {
      parsedJson = JSON.parse(t.json);
    } catch (err) {
      failed++;
      console.error(
        `FAIL ${t.file}:${t.line} ${t.slug} — not valid JSON: ${
          err instanceof Error ? err.message : err
        }`
      );
      continue;
    }

    // Not every $json$ block is a form template — some migrations carry
    // other JSON. A block with no `fields` array is left alone.
    if (
      typeof parsedJson !== "object" ||
      parsedJson === null ||
      !Array.isArray((parsedJson as { fields?: unknown }).fields)
    ) {
      continue;
    }

    checked++;
    const result = formSchema.safeParse(parsedJson);
    if (!result.success) {
      failed++;
      console.error(`FAIL ${t.file}:${t.line} ${t.slug}`);
      for (const issue of result.error.issues.slice(0, 4)) {
        console.error(`       ${issue.path.join(".") || "(root)"}: ${issue.message}`);
      }
    }
  }
}

if (failed > 0) {
  console.error(
    `\n${failed} template(s) would 404 in the app. ` +
      `Fix them against lib/staff/forms.ts before shipping.`
  );
  process.exit(1);
}

console.log(`${checked} form templates parse cleanly.`);
